package dnsmasq

import (
	"os"
	"path/filepath"
	"testing"
)

func TestSnippet(t *testing.T) {
	got, err := Snippet("127.0.0.1:5353")
	if err != nil {
		t.Fatal(err)
	}
	want := "# zakop-owned: generated by /etc/init.d/zakop\nserver=127.0.0.1#5353\n"
	if got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
}

func TestWriteRemove(t *testing.T) {
	dir := t.TempDir()
	path, err := Write(dir, "127.0.0.1:5353")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path); err != nil {
		t.Fatal(err)
	}
	if err := Remove(dir); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, FileName)); !os.IsNotExist(err) {
		t.Fatalf("snippet still exists or stat failed unexpectedly: %v", err)
	}
}
