package dnsmasq

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
)

const FileName = "zakop.conf"

func Snippet(listen string) (string, error) {
	host, port, err := net.SplitHostPort(listen)
	if err != nil {
		return "", err
	}
	if host == "" || port == "" {
		return "", fmt.Errorf("invalid DNS listen address %q", listen)
	}
	return fmt.Sprintf("# zakop-owned: generated by /etc/init.d/zakop\nserver=%s#%s\n", host, port), nil
}

func Write(dir string, listen string) (string, error) {
	text, err := Snippet(listen)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, FileName)
	return path, os.WriteFile(path, []byte(text), 0644)
}

func Remove(dir string) error {
	err := os.Remove(filepath.Join(dir, FileName))
	if os.IsNotExist(err) {
		return nil
	}
	return err
}
